---
title: "Incomplete Data Anlaysis Homework 1"
output:
  html_document: default
  word_document: default
always_allow_html: true
---

```{r Task3 Problem 1}
set.seed(1)
n = 500
z1 <- rnorm(n)
z2 <- rnorm(n)
z3 <- rnorm(n)


y1 = z1 + 1
y2 = 5 + 2 * z1 + z2
y2orig <- y2

a <- 2
b <- 0

# Create vector of missing data  
missing <- (a * (y1 -1) + b * (y2 - 5) + z3) < 0

# Creating missing values in y2
for (i in 1:length(y2)) {
  if (missing[i] == TRUE) {
    y2[i] <- NA
  }
}

summary(y2)
summary(y2orig)
var(y2orig, na.rm = T)
cor(y1, y2orig)
cor(y1, complete.cases(y2))

df <- data.frame("y2orig" = y2orig,
           "y2" = y2)

df

plot(density(y2[!is.na(y2)]), lwd = 2, col = "blue", main = "Marginal distributions for complete and MNAR (a = 2, b = 0)", xlab = "Value of Y2", xlim = c(-5,15))
lines(density(y2orig), lwd = 2, col = "dark green")
legend(8, 0.225, legend = c("Observed Y2", "Complete Y2"),
       col = c("blue", "dark green"), lty = c(1,1), lwd = c(2,2), bty = "n")
```

```{r Task 3 Problem 2}
set.seed(1)
fit <- lm(y2 ~ y1)
sigmaest <- sigma(fit)
pred <- fit$coefficients[1] + y1 * fit$coefficients[2] + rnorm(n, 0, sigmaest)
y2_completed <- ifelse(is.na(y2), pred, y2)

plot(density(y2_completed), lwd = 2, col = "blue", main = "Marginal distributions - complete & observed w/ imputations (a=2, b=0)",
     xlab = "Value of Y2", xlim = c(-5,15), ylim = c(0,0.3))
lines(density(y2orig), lwd = 2, col = "dark green")
legend(8.5, 0.2, legend = c("Y2 W/ Imputation", "Complete Y2"),
       col = c("blue", "dark green"), lty = c(1,1), lwd = c(2,2), bty = "n")
```

```{r Task 3 Problem 3}
a <- 0
b <- 2

# Create vector of missing data

y2 <- y2orig

missing <- (a * (y1 -1) + b * (y2 - 5) + z3) < 0



# Creating missing values in y2
for (i in 1:length(y2)) {
  if (missing[i] == TRUE) {
    y2[i] <- NA
  }
}

summary(y2)
summary(y2orig)
var(y2orig, na.rm = T)

df <- data.frame("y2orig" = y2orig,
           "y2" = y2)


plot(density(y2[!is.na(y2)]), lwd = 2, col = "blue" ,xlim = c(-5,15), main = "Marginal distributions for complete and MNAR (a = 0, b = 2)",
     xlab = "Value of Y2")
lines(density(y2orig), lwd = 2, col = "dark green")
legend(8.5, 0.3, legend = c("Observed", "Complete Y2"),
       col = c("blue", "dark green"), lty = c(1,1), lwd = c(2,2), bty = "n")
```

```{r Task 3 Problem 4}
set.seed(1)

fit <- lm(y2 ~ y1)
sigmaest <- sigma(fit)
pred <- fit$coefficients[1] + y1 * fit$coefficients[2] + rnorm(n, 0, sigmaest)
y2_completed <- ifelse(is.na(y2), pred, y2)

plot(density(y2_completed), lwd = 2, col = "blue", xlim = c(-5,15), main = "Marginal distributions - complete & observed w/ imputations (a=0, b=2)",
     xlab = "Value of Y2")
lines(density(y2orig), lwd = 2, col = "dark green")
legend(8.5, 0.275, legend = c("Y2 W/ Imputation", "Complete Y2"),
       col = c("blue", "dark green"), lty = c(1,1), lwd = c(2,2), bty = "n")

```

```{r Task4 Problem 1}
library(kableExtra)
library(tidyr)
load("databp.Rdata")

databp_complete <- databp[complete.cases(databp),]

df <- data.frame("Mean recov time" = 0,
           "Cor w Dose" = 0,
           "Cor w b-pressure" = 0)

df[1] <- mean(databp_complete$recovtime)

# Is Pearsons by default
df[2] <- cor(databp_complete$recovtime, databp_complete$logdose)

df[3] <- cor(databp_complete$recovtime, databp_complete$bloodp)


df_kab <- df %>%
  kable(caption = "Mean and Correlations for Complete Case") %>%
  kable_classic_2(full_width = F)

df_kab

```


```{r Task4 Problem 2}
databp_mean_imput <- databp
databp_mean_imput$recovtime[is.na(databp_mean_imput$recovtime)] <- mean(databp_mean_imput$recovtime, na.rm = T)

df <- data.frame("Mean recov time" = 0,
           "Cor w Dose" = 0,
           "Cor w b-pressure" = 0)

# Mean stays the same of course
df[1] <- mean(databp_mean_imput$recovtime)

# Is Pearsons by default
df[2] <- cor(databp_mean_imput$recovtime, databp_mean_imput$logdose)

df[3] <- cor(databp_mean_imput$recovtime, databp_mean_imput$bloodp)

df_kab <- df %>%
  kable(caption = "Mean and Correlations with imputed mean") %>%
  kable_classic_2(full_width = F)

df_kab
```

```{r Task4 Problem 3}
databp_reg_imput <- databp


fit <- lm(recovtime ~ logdose + bloodp, databp_reg_imput)
pred <- fit$coefficients[1] + databp_reg_imput$logdose * fit$coefficients[2] + databp_reg_imput$bloodp * fit$coefficients[3]

databp_reg_imput$recovtime <- ifelse(is.na(databp_reg_imput$recovtime), pred, databp_reg_imput$recovtime)

df[1] <- mean(databp_reg_imput$recovtime)

df[2] <- cor(databp_reg_imput$recovtime, databp_reg_imput$logdose)

df[3] <- cor(databp_reg_imput$recovtime, databp_reg_imput$bloodp)

df_kab <- df %>%
  kable(caption = "Mean and Correlations with regression imputation") %>%
  kable_classic_2(full_width = F)

df_kab
```


```{r Task4 Problem 4}
# Have to be careful because the noise could cause implausible answers

databp_stochreg_imput <- databp

set.seed(1)

fit <- lm(recovtime ~ logdose + bloodp, databp_stochreg_imput)
sigmaest <- sigma(fit)
pred <- fit$coefficients[1] + databp_stochreg_imput$logdose * fit$coefficients[2] + databp_stochreg_imput$bloodp * fit$coefficients[3] + rnorm(25, 0, sigmaest)


databp_stochreg_imput$recovtime <- ifelse(is.na(databp_stochreg_imput$recovtime), pred, databp_stochreg_imput$recovtime)

databp_stochreg_imput$recovtime <- ifelse(databp_stochreg_imput$recovtime <0, 0, databp_stochreg_imput$recovtime)

df[1] <- mean(databp_stochreg_imput$recovtime)

df[2] <- cor(databp_stochreg_imput$recovtime, databp_stochreg_imput$logdose)

df[3] <- cor(databp_stochreg_imput$recovtime, databp_stochreg_imput$bloodp)

df_kab <- df %>%
  kable(caption = "Mean and Correlations with stochastic regression imputation") %>%
  kable_classic_2(full_width = F)

df_kab

Df_Var <- data.frame("Stochastic Regression Variance" = NA,
           "Predictive Mean Match" = NA)

Df_Var[1] <- var(databp_stochreg_imput$recovtime)

```

```{r Task4 Problem 5}
databp_meanmatch <- databp

# Fits regression of recovery time on the complete variables
fit <- lm(recovtime ~ logdose + bloodp, databp_meanmatch)

# Makes prediction using regression
pred <- fit$coefficients[1] + databp_meanmatch$logdose * fit$coefficients[2] + databp_meanmatch$bloodp * fit$coefficients[3]

# Creates column of those predictions
databp_meanmatch$pred <- pred

# Creates column of those predictions to the power of 2
databp_meanmatch$pred2 <- pred^2

# smallestpred <- databp_meanmatch$pred2 - databp_meanmatch$pred2[4]
# smallestpred <- ifelse(smallestpred == 0, Inf, smallestpred)
# 
# databp_meanmatch$recovtime[smallestpred == smallestpred[min(smallestpred, na.rm = T) == smallestpred]]

# For loop that imputes values for missing data by finding which other subject has the smallest difference of squares
for (i in 1:length(pred)){
  if(is.na(databp_meanmatch$recovtime[i])){
    smallestpred <- abs(databp_meanmatch$pred2 - databp_meanmatch$pred2[i])
    smallestpred <- ifelse(smallestpred == 0, Inf, smallestpred)
    databp_meanmatch$recovtime[i] <- databp_meanmatch$recovtime[smallestpred == smallestpred[min(smallestpred, na.rm = T) == smallestpred]]
  }
}

#print(databp_meanmatch)

# Mean stays the same of course
# df <- data.frame(Mean = mean(databp_meanmatch$recovtime),
#                  Cor_Dose = cor(databp_meanmatch$recovtime, databp_meanmatch$logdose),
#                  Cor_Bloods = cor(databp_meanmatch$recovtime, databp_meanmatch$bloodp))

mean(databp_meanmatch$recovtime)

# Is Pearsons by default
cor(databp_meanmatch$recovtime, databp_meanmatch$logdose)

cor(databp_meanmatch$recovtime, databp_meanmatch$bloodp)


df[1] <- mean(databp_meanmatch$recovtime)

df[2] <- cor(databp_meanmatch$recovtime, databp_meanmatch$logdose)

df[3] <- cor(databp_meanmatch$recovtime, databp_meanmatch$bloodp)

df_kab <- df %>%
  kable(caption = "Mean and Correlations with predictive mean matching imputation") %>%
  kable_classic_2(full_width = F)

df_kab


Df_Var[2] <- var(databp_meanmatch$recovtime)

# Standard Errors
Df_Var/sqrt(25)
# The obvious advantage of this method is that it is less likely to return implausible values. 
# Disadvantage would be that it has reduced variance.
```